### ISSUE TITLE
Indexing the GRANDMA grade

### ISSUE THREAD

**Issue by jgducoin** [mcoughlin/gwemopt#14]
If I'm right the VOEvents that GRANDMA will send to the telescope contain the grade index (which indicate which grade was used by the ObsStrat). At the moment the information is stored in lines 415 and 426 of ToO_manager.py (#13 ). I don't know how @santier14 want to include it on the VOEvent.
Maybe you can fix this @santier14.

**Comment by santier14** [comment]
on line #439 grade_vec.append(np.round(prob,4)) I can fix the correct value ...

**Comment by mcoughlin** [comment]
@santier14 @jgducoin can this be closed?

**Comment by santier14** [comment]
oui
