### ISSUE TITLE
healpy.ud_grade() breaking the distance information

### ISSUE THREAD

**Issue by jgducoin** [mcoughlin/gwemopt#18]
Having a look on the outputed galaxies for GW170817 I figured out that the galaxies selected where wrong due to a bad distance selection, see:

![gal](https://user-images.githubusercontent.com/44273935/53650848-c52d4880-3c45-11e9-9764-857a454a1930.png)

Tests showed that this come from the healpy.ud_grade() function which break the distance information when the nside is not the default one (the one given in the fits file header), see for example dist_mu for GW170817:

![screenshot from 2019-03-01 16-58-56](https://user-images.githubusercontent.com/44273935/53650930-f148c980-3c45-11e9-8d29-c2e1550f01d9.png)

In ToO_manager.py we put by hand a value to params["nside"] and in utils.py the function read_skymap() use healpy.ud_grade() with this given nside. If I put by hand the default value for the nside  I have a good list of galaxies, see:

![gal_2](https://user-images.githubusercontent.com/44273935/53651144-51d80680-3c46-11e9-9d2f-1731203ba979.png)

I think that the best thing to do is just to fit with the nside given by the skymap and don't use healpy.ud_grade() (which is for me a black box), but that mean that we need to fetch the nside info from the skymap and work with it. If so we need something like:
`nside = hp.npix2nside(len(skymap))`

agree?

**Comment by mcoughlin** [comment]
@jgducoin can we close this now?

**Comment by jgducoin** [comment]
yes!
