### ISSUE TITLE
scheduler.py no config_struct["telescope"]

### ISSUE THREAD

**Issue by jgducoin** [mcoughlin/gwemopt#38]
There is an issue with the line 474 of scheduler.py.
`coverage_struct["telescope"] = [config_struct["telescope"]]*len(coverage_struct["filters"])`

I see that you changer it twice, i don't know what you are exactly trying to do here, but it seems that this is bugging using GRANDMA telescope.
`config_struct["telescope"]` does not exist as it is not in the config file of telescopes.
@mcoughlin

**Comment by mcoughlin** [comment]
This was fixed by @shreyasahasram08 and @dcorre.
